export const GET_ALL_ADMIN_ORDER_REQUEST = "GET_ALL_ADMIN_ORDER_REQUEST";
export const GET_ALL_ADMIN_ORDER_SUCCESS = "GET_ALL_ADMIN_ORDER_SUCCESS";
export const GET_ALL_ADMIN_ORDER_FAIL = "GET_ALL_ADMIN_ORDER_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
